GET http://localhost:8080/sales/events

###
GET http://localhost:8080/sales/users

###
POST http://localhost:8080/sales/events
Content-Type: application/json

{
    "description": "Curso de Spring Boot",    
    "date": "2025-08-30T13:30:00",
    
    "startSales": "2025-08-01T22:00:00",
    "endSales": "2025-08-29T23:59:59",
    
    "price": 350.7
}

###

POST http://localhost:8080/sales
Content-Type: application/json

{
    "userId": "412aea29-305f-4a9a-831b-4b79335d1135",
    "eventId": "ff56e53a-0e48-4bf4-b30c-6214d31730c9"
}

###
GET http://localhost:8080/sales
