GET http://localhost:3000/users/status

###
GET http://localhost:3000/users

###
GET http://localhost:3000/users/a3d0fee0-8a0c-4cbf-93c0-ed3d0057218f


###
GET http://localhost:3000/users/byname/fer

###
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Hugo",
    "creditCardNumber": "123456789",
    "email": "hugo@web.ufop.edu.br",
    "password": "123456"
}

###
PUT http://localhost:3000/users
Content-Type: application/json

{
    "id": "02c95281-bfa8-4859-93dc-1508ed511901",
    "name": "Hugo Oliveira",
    "creditCardNumber": "987654321",

}

###
PUT http://localhost:3000/users/password
Content-Type: application/json

{
    "id": "02c95281-bfa8-4859-93dc-1508ed511901",
    "email": "hugo@web.ufop.edu.br",
    "oldPassword": "123456",
    "newPassword": "654321"

}

###
DELETE http://localhost:3000/users/remove
Content-Type: application/json

{
    "id": "02c95281-bfa8-4859-93dc-1508ed511901"
}

###

GET http://localhost:3000/ccn

###
POST http://localhost:3000/ccn
Content-Type: application/json

{
    "name": "American Express"
}

###
PUT http://localhost:3000/users/creditcard
Content-Type: application/json

{
    "id": "d1f8e7b3-5cf0-41be-bf6f-fc9daea151f3",
    "creditCardNumber": "789123456012",
    "creditCardNetworkId": "4743f630-8525-461c-8f83-fea1152f0d41"

}